### ISSUE TITLE
having trouble creating hh-suite database

### ISSUE THREAD

**Issue by farhanquadir** [soedinglab/hh-suite#129]
:exclamation: Make to check out our [User Guide](https://github.com/soedinglab/hh-suite/wiki).
I am attempting to create a hh-suite database from a directory containing many .a3m files. So far I am currently using hh-suite version 3.
When I pass the following command:
python /storage/hpc/data/fqg7h/hh-suite/scripts/hhsuitedb.py --cpu 1 -o /storage/hpc/data/fqg7h/T0951_db/T0951_db --ia3m /storage/hpc/data/fqg7h/T0951_a3m/ --force

I get an error. The file /storage/hpc/data/fqg7h/hmmer-3.1b2-linux-intel-x86_64/src/T0951_db/T0951_db_hhm.ffindex is not found in the directory while the other files are empty. 

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps.

## HH-suite Output (for bugs)
ffindex_build: fread: Is a directory
/storage/hpc/data/fqg7h/hh-suite/lib/ffindex/src/ffindex.c:231 ffindex_insert_filestream: : Is a directory
ffindex_apply_mpi: Problem with data file. Is the file empty or is another process reading it?: Invalid argument
/storage/hpc/data/fqg7h/hh-suite/lib/ffindex/src/ffindex_apply_mpi.c:367 ffindex_index_parse: /tmp/tmptqi8on/large.ffindex: Invalid argument
*** The MPI_Finalize() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[lewis4-r710-login-node223:23941] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[62006,1],0]
  Exit code:    1
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/storage/hpc/data/fqg7h/hh-suite/scripts/hhsuitedb.py", line 482, in <module>
    main()
  File "/storage/hpc/data/fqg7h/hh-suite/scripts/hhsuitedb.py", line 478, in main
    check_database(options.output_basename, options.nr_cores, options.force_mode)
  File "/storage/hpc/data/fqg7h/hh-suite/scripts/hhsuitedb.py", line 376, in check_database
    calculate_hhm(threads, output_basename+"_a3m", output_basename+"_hhm")
  File "/storage/hpc/data/fqg7h/hh-suite/scripts/hhsuitedb.py", line 106, in calculate_hhm
    check_call(" ".join(["mpirun", "-np", threads, "ffindex_apply_mpi", a3m_base_path+".ffdata", large_a3m_index, "-d", hhm_base_path+".ffdata", "-i", hhm_base_path+".ffindex", "--", "hhmake", "-v", str(0), "-i", "stdin", "-o" ,"stdout"]), shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mpirun -np 1 ffindex_apply_mpi /storage/hpc/data/fqg7h/T0951_db/T0951_db_a3m.ffdata /tmp/tmptqi8on/large.ffindex -d /storage/hpc/data/fqg7h/T0951_db/T0951_db_hhm.ffdata -i /storage/hpc/data/fqg7h/T0951_db/T0951_db_hhm.ffindex -- hhmake -v 0 -i stdin -o stdout' returned non-zero exit status 1

Please make sure to post the complete output of the tool you called. Please use [gist.github.com](https://gist.github.com).

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Linux -Centos cluster
Include as many relevant details about the environment you experienced the issue in.
* Version/Git commit used:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by Dureshahwarwaseem** [comment]
Having trouble in accessing database uniclust30_2018_08on linux ..when i access the database uniclust30_2018_08 with following commands 
hhblits -cpu 4 -i data/query.seq -d databases/uniclust30_2018_08/uniclust30_2018_08 -oa3m query.a3m -n 2 
So an error message prompt that could'nt open uniclust30_2018_08 ffdata file .. Kindly help how to solve this issue?

**Comment by kaihami** [comment]
@Dureshahwarwaseem 
Two points:
1-) Have you downloaded the Uniclust30 DB?
2-) Provide the full path of the DB as well the query.
Seems you are not passing the right DB path.

`hhblits -cpu 4 -i /data/query.seq -d /databases/uniclust30_2018_08/uniclust30_2018_08 -oa3m query.a3m -n 2`
