### ISSUE TITLE
hhmakemodel.py : list index out of range

### ISSUE THREAD

**Issue by AntoineLabeeuw** [soedinglab/hh-suite#135]
Hi, me and @diegozea are using HH-suite3, v 3.2.0, commit d335e62  on Ubuntu 16.04.5 LTS.

When using hhmakemodel.py with a .hhr coming from hhsearch, it throws an error :
> python3 hhmakemodel.py file.hhr <path_to_pdb> out.pir ./

```Traceback (most recent call last):
  File "/home/labeeuw/Documents/hh-suite/build/scripts/hhmakemodel.py", line 2400, in <module>
    main()
  File "/home/labeeuw/Documents/hh-suite/build/scripts/hhmakemodel.py", line 2385, in main
    glob_seq = derive_global_seq(processed_query_grid, query_name, query_chain) # derive query sequence
  File "/home/labeeuw/Documents/hh-suite/build/scripts/hhmakemodel.py", line 663, in derive_global_seq
    global_seq.append(processed_query_grid.get_col_residue(col))
  File "/home/labeeuw/Documents/hh-suite/build/scripts/hhmakemodel.py", line 287, in get_col_residue
    if not self.is_empty(row, col):
  File "/home/labeeuw/Documents/hh-suite/build/scripts/hhmakemodel.py", line 197, in is_empty
    return self._cells[row][col] == EMPTY
IndexError: list index out of range
```
## Steps to Reproduce (for bugs)  
Attached to this are the files i've got from hhblits and hhsearch  
Everything was done with the latest databases available  
[O00159.zip](https://github.com/soedinglab/hh-suite/files/3182942/O00159.zip)

**Comment by milot-mirdita** [comment]
The structure modeling part of the hh-suite (hhpred and hhmakemodel) is currently unsupported due to a lack of funding and manpower. We would be happy to merge any pull requests that fix it though.

With that said, could you try to explicitly specify which hits it should try to use for modeling (with the `-m` parameter).

**Comment by AntoineLabeeuw** [comment]
Hi
I managed to fix it, the error was that the rows were not of the same sizes, resulting in a list index out of range.
the pull request #154 fixes it, as well as some other errors i encountered, such as the modelling with modeller that didn't work because of the cif chain renaming in the script. the structure modelling part should now work more reliably
