### ISSUE TITLE
hhsuitedb.py fails on building database from directory of a3m files

### ISSUE THREAD

**Issue by DanBuchan** [soedinglab/hh-suite#92]
HHSuite version 3.03
Centos 7, gcc 4.8.5
mpirun 3.0.0a1

```
> python /scratch0/NOT_BACKED_UP/dbuchan/Applications/hh-suite-3/scripts/hhsuitedb.py --cpu 2 -o fbe1b3b4-3f22-11e8-8a27-989096c13ee6-mydb/mydb --ia3m fbe1b3b4-3f22-11e8-8a27-989096c13ee6-mya3m/

Unlinking entries from '/tmp/tmpt8iqy66i/files.dat'
ffindex_apply_mpi: Problem with data file. Is the file empty or is another process reading it?: Invalid argument
/scratch0/NOT_BACKED_UP/dbuchan/Applications/hh-suite-3/lib/ffindex/src/ffindex_apply_mpi.c:367 ffindex_index_parse: /tmp/tmppro77st1/large.ffindex: Invalid argument
*** The MPI_Finalize() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[1s0kg52.thecrick.org:12126] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[50141,1],1]
  Exit code:    1
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch0/NOT_BACKED_UP/dbuchan/Applications/hh-suite-3/scripts/hhsuitedb.py", line 482, in <module>
    main()
  File "/scratch0/NOT_BACKED_UP/dbuchan/Applications/hh-suite-3/scripts/hhsuitedb.py", line 478, in main
    check_database(options.output_basename, options.nr_cores, options.force_mode)
  File "/scratch0/NOT_BACKED_UP/dbuchan/Applications/hh-suite-3/scripts/hhsuitedb.py", line 376, in check_database
    calculate_hhm(threads, output_basename+"_a3m", output_basename+"_hhm")
  File "/scratch0/NOT_BACKED_UP/dbuchan/Applications/hh-suite-3/scripts/hhsuitedb.py", line 106, in calculate_hhm
    check_call(" ".join(["mpirun", "-np", threads, "ffindex_apply_mpi", a3m_base_path+".ffdata", large_a3m_index, "-d", hhm_base_path+".ffdata", "-i", hhm_base_path+".ffindex", "--", "hhmake", "-v", str(0), "-i", "stdin", "-o" ,"stdout"]), shell=True)
  File "/usr/local/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mpirun -np 2 ffindex_apply_mpi fbe1b3b4-3f22-11e8-8a27-989096c13ee6-mydb/mydb_a3m.ffdata /tmp/tmppro77st1/large.ffindex -d fbe1b3b4-3f22-11e8-8a27-989096c13ee6-mydb/mydb_hhm.ffdata -i fbe1b3b4-3f22-11e8-8a27-989096c13ee6-mydb/mydb_hhm.ffindex -- hhmake -v 0 -i stdin -o stdout' returned non-zero exit status 1

```

To help us debugging your issue, please make sure you

- [*] included the HHsuite version or commit ID
- [*] added information about your operating system and compiler (if building from source)
- [*] checked the [user-guide](https://github.com/soedinglab/hh-suite/blob/master/hhsuite-userguide.pdf) for available documentation
- [*] ideally also included a minimal example for us to reproduce the issue

**Comment by milot-mirdita** [comment]
Could you retry with the `--force` parameter. That might solve your issue.
